### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by Zache** [Daniel15/JSPool#12]
```
System.Collections.Generic.Dictionary`2.get_Item(TKey key):12
 JSPool.JsPool.TakeEngine(IJsEngine engine):0
 JSPool.JsPool.GetEngine(Nullable`1 timeout):22
 React.JavaScriptEngineFactory.GetEngine():21
 System.Lazy`1.CreateValue():198
 System.Lazy`1.LazyInitValue():134
 React.ReactEnvironment.get_Engine():25
 React.ReactEnvironment.Execute[T](String code):0
 React.ReactEnvironment.GetInitJavaScript():18
 React.Web.Mvc.HtmlHelperExtensions.ReactInitJavaScript(HtmlHelper htmlHelper):5
 --snip
```

Any idea as to what causes this?

**Comment by Daniel15** [comment]
Most likely fixed with #13

**Comment by FrankBakkerNl** [comment]
It seems like this Issue is not yet resolved, we are getting this same exception / stack trace in our production environment right now.
Exception: System.Collections.Generic.KeyNotFoundException
Message: The given key was not present in the dictionary.
Source: mscorlib
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at JSPool.JsPool.TakeEngine(IJsEngine engine)
   at JSPool.JsPool.GetEngine(Nullable`1 timeout)
   at Framework.React.SiteSpecificJavaScriptEngineFactory.GetEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at React.ReactEnvironment.HasVariable(String name)

Looks like the problem is in the line 

var metadata = _metadata[engine];

at

https://github.com/Daniel15/JSPool/blob/98e68eb819f6e78e35f2717182d168bd59bd58b1/src/JSPool/JsPool.cs#L182


I think this should use a TryGetValue() like is done in some of the other methods
